version: 1.0.{build}
configuration: Release
platform: x86
before_build:
  - nuget restore
build:
  project: SortingAlgorithms.sln
  verbosity: minimal
# test_script:
# - cmd: vstest.console Release\x86\UnitTests.dll /logger:Appveyor
artifacts:
- path: Release
  name: SortingAlgotithms
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"Release\x86\UnitTests.dll -noshadow" -output:"coverage.xml"
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t baO9xvs6PPZEeljwyZ1BE2bCtK0r86BD6