version: 1.0.{build}
configuration: Release
platform: x86
before_build:
  - nuget restore
build:
  project: SortingAlgorithms.sln
  verbosity: minimal
test_script:
- cmd: vstest.console Release\x86\UnitTests.dll /logger:Appveyor
artifacts:
- path: Release
  name: SortingAlgotithms
after_test:
    - cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vSTest.console.exe" -targetargs:"C:\projects\SortingAlgotithms\Release\x86\UnitTests.dll" -output:coverage.xml
    - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -r baO9xvs6PPZEeljwyZ1BE2bCtK0r86BD6