version: 1.0.{build}

image:
- Visual Studio 2017
- Visual Studio 2015

platform:
  - x86
  - x64

configuration:
- Debug
- Release

environment:
  matrix:
  - USE_SHARED: 0
  - USE_SHARED: 1

before_build:
- cmd:  mkdir build && cd build
- cmd: cmake -H.. -DUSE_SHARED=%USE_SHARED%

build:
  project: build/ALL_BUILD.vcxproj
  verbosity: minimal
  
artifacts:
  - path: build/$(CONFIGURATION)
    name: build/$(CONFIGURATION)