version: 1.0.{build}
configuration: Debug
platform: x86
before_build:
  - nuget restore
build:
  project: SortingAlgorithms.sln
  verbosity: minimal
after_build:
- cmd: valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes --trace-children=yes ./Debug/x86/Main.exe
test_script:
  - cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vSTest.console.exe" -targetargs:"C:\projects\SortingAlgotithms\Debug\x86\UnitTests.dll /Platform:x86 /logger:Appveyor" -output:coverage.xml
artifacts:
  - path: Debug
    name: SortingAlgotithms
after_test:
  - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -r baO9xvs6PPZEeljwyZ1BE2bCtK0r86BD6